Маркировка пилонов: Добавлен плагин
Bim4Everyone/KRExtensions pull request #22
Opened 2024-11-05 14:49 UTC by DivinN

Разработать плагин, который по информации из параметров пилона заполняет параметр пилона "Марка", а также размещает марки пилонов на активном виде.

Для запуска необходимо перейти на план, выбрать пилоны и запустить плагин. По итогу работы будет показан отчет:
![image](https://github.com/user-attachments/assets/f21c3f79-af7a-4db8-8ae7-33a341ca9d05)

Холст: https://app.holst.so/board/e51ecb86-81aa-41f0-83b6-a3e587b5d946?objectId=8eb8c63b-ebc3-4fde-ad7b-58fbd5521a9b

2024-11-15 10:56 UTC, dosymep requested changes

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +              if elem.Category.Name.Contains('Несущие колонны') and elem.Name.Contains('Пилон')]
сравнивать категории нужно только по `BuiltInCategory`

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +        if material.Name.Contains('Бетон с Пенетроном'):
рекомендую вынести данную строку в переменную

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +    with revit.Transaction("КР: Маркировка пилонов"):
мы обычно пишем `BIM:`

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +                pylon.GetParam(param_name_for_write).Set(string_for_write)
в платформе есть метод `SetParamValue`

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +                report_about_write.append([pylon.Name, output.linkify(pylon.Id), error, '', pylon])
в одной строке несколько раз один и тот же идентфикатор написан

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +    families = FilteredElementCollector(doc).OfCategory(BuiltInCategory.INVALID).OfClass(Family)
удали `OfCategory(BuiltInCategory.INVALID)`

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +        tag_symbol_name = tag_symbol.get_Parameter(BuiltInParameter.SYMBOL_NAME_PARAM).AsString()
используй платформу

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +            tag_symbol_name = tag_symbol.get_Parameter(BuiltInParameter.SYMBOL_NAME_PARAM).AsString()
используй платформу

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +    with revit.Transaction("КР: Размещение марок пилонов"):
обычно пишем `BIM:`

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +
че это такое?

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +    doc.Regenerate()
удали, код должен работать без случайных вызовов регенерации документа

2024-11-15 10:56 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +param_name_for_height = 'ФОП_РАЗМ_Высота'
Запиши параметры в платформу, и используй их из платформы

2024-11-18 13:07 UTC, DivinN commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +    doc.Regenerate()
Там по другому не сработает, оставил коммент

2024-11-21 07:03 UTC, dosymep requested changes

2024-11-21 07:03 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +struct_columns_category_id = Category.GetCategory(doc, BuiltInCategory.OST_StructuralColumns).Id
можно написать проще `ElementId(BuiltInCategory.OST_StructuralColumns)`

2024-11-21 07:03 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +'''Ключевое слово в имени типа элемента для фильтрации нужных элементов'''
комментарии пишутся до кодовой конструкции

2024-11-21 07:03 UTC, dosymep commented on КР.tab/Документация.panel/Маркировка пилонов.pushbutton/script.py
> +        tag_symbol_name = str(tag_symbol.GetParamValue(BuiltInParameter.SYMBOL_NAME_PARAM))
зачем конвертировать в строку строковый параметр?

2024-11-25 10:40 UTC, dosymep approved these changes

2024-11-25 10:40 UTC, merged